version: '3.8'

services:
  # Main FastAPI Application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/tiktok_analytics
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=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
    volumes:
      - ./app:/app/app
      - ./chroma_db:/app/chroma_db
    depends_on:
      - postgres
      - redis

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tiktok_analytics
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 